import {
  Bot,
  CalendarClock,
  Clock,
  GitFork,
  Github,
  Gitlab,
  MessageSquareReply,
  Play,
  Webhook,
  Zap,
  Box,
  Code,
  FileText,
  Flag,
  GitBranch,
  GitPullRequest,
  Hammer,
  ListChecks,
  Rocket,
  SearchCheck,
  ShieldCheck,
  Split,
  Terminal,
  TestTube,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  box: Box,
  bot: Bot,
  flag: Flag,
  "git-branch": GitBranch,
  "git-pull-request": GitPullRequest,
  "list-checks": ListChecks,
  hammer: Hammer,
  "search-check": SearchCheck,
  wrench: Wrench,
  split: Split,
  terminal: Terminal,
  code: Code,
  "file-text": FileText,
  rocket: Rocket,
  "shield-check": ShieldCheck,
  "test-tube": TestTube,
  zap: Zap,
  clock: Clock,
  "calendar-clock": CalendarClock,
  play: Play,
  github: Github,
  gitlab: Gitlab,
  webhook: Webhook,
  "git-fork": GitFork,
  "message-square-reply": MessageSquareReply,
};

export function BlockIcon({ name, className }: { name: string; className?: string }) {
  const Icon = ICONS[name] ?? Box;
  return <Icon className={className} />;
}
